[build-system]
requires = ["hatchling", "ziggy-pydust==0.23.2"]
build-backend = "hatchling.build"

[project]
name = "fibonacci"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = ["fibonacci"]
artifacts = ["fibonacci/*.so"]

[tool.hatch.build.targets.wheel.hooks.custom]

# [tool.pydust]
# self_managed = true # Pydust will build pydust.build.zig for us, but we'll manage our own build.zig

[[tool.pydust.ext_module]]
name = "fibonacci._lib"
root = "src/fib.zig"